# -*- coding: utf-8 -*-
"""K_Means.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LmAEmV1AbfwDFqXoDleGSlg4rNXEzXLm
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

df = pd.read_csv("/content/Mall_Customers.csv")

print("First 5 rows:")
print(df.head())

print("\nDataset Info:")
print(df.info())

df_model = df.drop("CustomerID", axis=1)

X = df_model[["Annual Income (k$)", "Spending Score (1-100)"]]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

inertia = []
K_range = range(1, 11)

for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(X_scaled)
    inertia.append(kmeans.inertia_)

inertia

plt.figure(figsize=(7, 5))
plt.plot(K_range, inertia, marker='o')
plt.xlabel("Number of Clusters (K)")
plt.ylabel("Inertia")
plt.title("Elbow Method for Optimal K")
plt.show()

kmeans = KMeans(n_clusters=5, random_state=42, n_init=10)
clusters = kmeans.fit_predict(X_scaled)

df["Cluster"] = clusters

plt.figure(figsize=(8, 6))
sns.scatterplot(
    x="Annual Income (k$)",
    y="Spending Score (1-100)",
    hue="Cluster",
    palette="tab10",
    data=df
)
plt.title("Customer Segmentation using KMeans")
plt.show()

df.to_csv("segmented_mall_customers.csv", index=False)

print("\nSegmentation completed successfully!")

